auction_index:
    path: /
    controller: App\Controller\AuctionController::indexAction

auction_details:
    path: auction/details/{id}
    controller: App\Controller\AuctionController::detailsAction

offer_buy:
    path: /auction/buy/{id}
    methods:  [POST]
    controller: App\Controller\OfferController::buyAction
    
offer_bid:
    path: /auction/bid/{id}
    methods:  [POST]
    controller: App\Controller\OfferController::bidAction

my_auction_index:
    path: /my
    controller: App\Controller\MyAuctionController::indexAction

my_auction_details:
    path: my/auction/details/{id}
    controller: App\Controller\MyAuctionController::detailsAction

my_auction_add:
    path: /my/auction/add
    controller: App\Controller\MyAuctionController::addAction

my_auction_edit:
    path: /my/auction/edit/{id}
    controller: App\Controller\MyAuctionController::editAction

my_auction_delete:
    path: /my/auction/delete/{id}
    methods:  [DELETE]
    controller: App\Controller\MyAuctionController::deleteAction

my_auction_finish:
    path: /my/auction/finish/{id}
    methods:  [POST]
    controller: App\Controller\MyAuctionController::finishAction