auction_index:
    path: /
    controller: App\Controller\AuctionController::indexAction

auction_details:
    path: auction/details/{id}
    controller: App\Controller\AuctionController::detailsAction
    
auction_add:
    path: /auction/add
    controller: App\Controller\AuctionController::addAction

auction_edit:
    path: /auction/edit/{id}
    controller: App\Controller\AuctionController::editAction

auction_delete:
    path: /auction/delete/{id}
    methods:  [DELETE]
    controller: App\Controller\AuctionController::deleteAction

auction_finish:
    path: /auction/finish/{id}
    methods:  [POST]
    controller: App\Controller\AuctionController::finishAction
    
offer_buy:
    path: /auction/buy/{id}
    methods:  [POST]
    controller: App\Controller\OfferController::buyAction
    
offer_bid:
    path: /auction/bid/{id}
    methods:  [POST]
    controller: App\Controller\OfferController::bidAction

my_auction_index:
    path: /my
    controller: App\Controller\MyAuctionController::indexAction

my_auction_details:
    path: my/auction/details/{id}
    controller: App\Controller\MyAuctionController::detailsAction