auction_index:
    path: /
    controller: App\Controller\AuctionController::indexAction

auction_details:
    path: /details/{id}
    controller: App\Controller\AuctionController::detailsAction
    
auction_add:
    path: /auction/add
    controller: App\Controller\AuctionController::addAction

auction_edit:
    path: /auction/edit/{id}
    controller: App\Controller\AuctionController::editAction
